name: "Build & Test"

on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:
  workflow_dispatch:
    inputs:
      override-cdt:
        description: 'Override cdt target'
        type: string
      override-cdt-prerelease:
        type: choice
        description: Override cdt prelease
        options:
        - default
        - true
        - false
      override-eos-system-contracts:
        description: 'Override eos-system-contracts ref'
        type: string

permissions:
  packages: read
  contents: read

defaults:
  run:
    shell: bash

jobs:
  platform-cache:
    name: Platform Cache
    uses: AntelopeIO/platform-cache-workflow/.github/workflows/platformcache.yaml@v1
    permissions:
      packages: write
      contents: read
    with:
      runs-on: '["self-hosted", "enf-x86-beefy"]'
      platform-files: |
        .cicd/platforms
        tools/reproducible.Dockerfile:builder

  tests:
    name: Tests (${{matrix.cfg.name}})
    needs: [platform-cache]
    strategy:
      fail-fast: false
      matrix:
        include:
          - cfg: {name: 'ubuntu20',      base: 'ubuntu20', builddir: 'ubuntu20'}
    runs-on: ["self-hosted", "enf-x86-hightier"]
    container:
      image: ${{fromJSON(needs.platform-cache.outputs.platforms)[matrix.cfg.base].image}}
      options: --security-opt seccomp=unconfined --mount type=bind,source=/var/lib/systemd/coredump,target=/cores
    steps:
      - uses: actions/checkout@v4
      - name: Run Parallel Tests
        run: |
          ls -la /cores
          g++ crash.cpp -O3 -o crash
          ./crash
          sleep 2
          ls -la /cores
      - name: Upload core files from failed tests
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: ${{matrix.cfg.name}}-tests-logs
          if-no-files-found: ignore
          path: /cores
